---
kind: pipeline
name: jbtech-timeoff

steps:
  # - name: Notify
  #   image: drillster/drone-email
  #   settings:
  #     host:
  #       from_secret: smtp_server
  #     port:
  #       from_secret: smtp_port
  #     username:
  #       from_secret: smtp_username
  #     password:
  #       from_secret: smtp_password
  #     from: drone@juanbaptiste.tech
  #     recipients: [ juan@juanbaptiste.tech ]
  #   when:
  #     status: [ success, changed, failure ]

  - name: docker
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      context: .
      registry: docker.io
      repo: juanluisbaptiste/timeoff
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: [ latest ]
    when:
      event:
        - push
        - tag

  - name: publish-timeoff
    image: appleboy/drone-ssh
    settings:
      host: timeoff.juanbaptiste.tech
      port: 22
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      script:
        # - /bin/bash ./deploy.sh timeoff
        - echo "Testing drone deployment !!"
        - touch /tmp/test
    when:
      branch:
        - master
      event:
        - push